stages:
  - build
  - test
  - deploy

variables:
  VERSION: luna-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_TAG: $CI_COMMIT_BRANCH

include:
  - local: ".gitlab-ci/build.yml"
  - local: ".gitlab-ci/test.yml"
  - local: ".gitlab-ci/deploy.yml"
