version: "3"

services:
  luna-frontend:
    restart: always
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    image: ${CI_REGISTRY_IMAGE}/:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - ${APP_PORT:-3002}:3000