.build_commom:
  tags:
    - ssh
    - luna
  stage: build
  script:
    - env > .env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker compose -f docker-compose.build.yml build --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE --build-arg DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG
    

build_production:
  extends: 
    - .build_commom
  environment:
    name: prod
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DOCKER_IMAGE_TAG: "latest"
  script: 
    - docker push $CI_REGISTRY

build_homol:
  extends: 
    - .build_commom
  environment:
    name: homol
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_BRANCH != "homologacao"'
      variables:
          DOCKER_IMAGE_TAG: "homologacao"
  script: 
    - docker push $CI_REGISTRY

build_staging:
  extends:
    - .build_commom
  environment:
    name: staging
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
          DOCKER_IMAGE_TAG: "commit-checked"
  script:
    - docker rmi $CI_REGISTRY_IMAGE/:$DOCKER_IMAGE_TAG