.test_common:
  stage: test
  dependencies:
    - build
  tags:
    - ssh
    - luna
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker compose run --rm luna-test

test_production:
  extends: 
    - .test_common
  environment:
    name: prod
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DOCKER_IMAGE_TAG: "latest"

test_homol:
  extends: 
    - .test_common
  environment:
    name: homol
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_BRANCH == "homologacao"'
      variables:
          DOCKER_IMAGE_TAG: "homologacao"

test_staging:
  extends: 
    - .test_common
  environment:
    name: staging
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_BRANCH != "homologacao" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      variables:
          DOCKER_IMAGE_TAG: "staging"