// tslint:disable
/**
 * SOLAR API
 * Solução Avançada em Atendimento de Refererência (SOLAR)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
