declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_THEME_COLOR_PRIMARY_MAIN: string
    NEXT_PUBLIC_THEME_COLOR_SECONDARY_MAIN: string
    NEXT_PUBLIC_THEME_COLOR_BACKGROUND_DEFAULT: string
    NEXT_PUBLIC_THEME_COLOR_BACKGROUND_PAPER: string
    TOKEN_SOLAR: string
    ENDPOINT_SOLAR: string
  }
}
